### PR TITLE
Expect the office group in the benchmark seed tests

### PR DESCRIPTION
**Pull request by S3333F**
## Description

Two unrelated test faults, both found while checking whether the uv image in #122 broke anything.
Neither is caused by that change and neither is visible in CI.

Three tests in `validator/tests/test_bench_full_eval.py` predate the office family and still
describe six benchmark groups. They sit behind `--run-full`, which CI does not pass, so they have
been failing unreported since `type7_office` was added. The same three fail identically in an image
built with pip and one built with uv.

Separately, the wheel fixture in `conftest.py` copies the whole repository and its ignore list has
no entry for a virtualenv. #122's install instructions create `.venv` in the repository root, its
`bin/python` points at the host interpreter, and a run inside the container follows that symlink to
a path that does not exist there. Every test needing a built wheel then errors before it runs.

Fixes # (issue)

### Related Tasks

- Task ID: wPNfkuY3
- Related tasks/PRs (other repos): none. Follows #122, which is where the failures were noticed.

### Type of Change

- [x] Bug fix
- [ ] New feature or capability
- [ ] Refactor / cleanup (no behavior change)
- [ ] Performance
- [ ] Documentation
- [ ] Tooling, CI, or infrastructure

### What does this PR change?

- `test_ram_estimates_are_defined_per_group` was missing `type7_office`. It now carries `1900.0`,
  the value `swarm/benchmark/engine_parts/dispatch.py:61` defines.
- `test_save_and_load_type_seeds` and `test_load_type_seeds_accepts_legacy_payload` built their
  payload from the global `BENCH_GROUP_ORDER` and then loaded it for `cf_autopilot` and
  `cf_search_and_rescue`. Neither family has office maps, so `_load_type_seeds` correctly returned
  six groups and the tests read that as a failure. They now build from `family_bench_groups(...)`.
- One test added stating the rule the two above depend on.
- `conftest.py` skips `.venv` and `venv` when copying the source the wheel is built from, and the
  ignore list moves into `wheel_source_ignore()` so a test can assert against the patterns the
  fixture actually uses rather than a copy of them.
- One test added building a repository with a deliberately dangling `.venv/bin/python` and asserting
  the copy skips it.

The second point is the one worth a reviewer's attention. Adding `type7_office` to those two
expectations would also have made them pass, and would have been wrong: it would assert that a
seed file loaded for autopilot carries office seeds, which is the opposite of what
`_normalize_type_seeds` is for. Confirmed at runtime:

```
family_bench_groups("cf_autopilot")          -> 6 groups, no type7_office
family_bench_groups("cf_search_and_rescue")  -> 6 groups, no type7_office
"type7_office" in BENCH_GROUP_ORDER          -> True
```

No production code changes.

### How was this tested?

- Commands run, in an image built from `.docker/Dockerfile` on this branch:
  - `pytest -q validator/tests/test_bench_full_eval.py -n4 --run-full --run-e2e`
  - `pytest -q validator/tests miner/tests -n8 --dist worksteal --run-full --run-e2e`
- Result: 28 passed on the file; 1159 passed, 2 skipped, 0 failed on the full opt-in run.

The full opt-in run was done twice over, once in an image built with pip and once with uv, to
establish these failures were not caused by #122:

<details>
<summary>Before this branch — both images, same three failures</summary>

```
##### swarm-pip-today (pip) #####
FAILED validator/tests/test_bench_full_eval.py::test_ram_estimates_are_defined_per_group
FAILED validator/tests/test_bench_full_eval.py::test_save_and_load_type_seeds
FAILED validator/tests/test_bench_full_eval.py::test_load_type_seeds_accepts_legacy_payload
3 failed, 1155 passed

##### swarm-uv-new (uv) #####
FAILED validator/tests/test_bench_full_eval.py::test_ram_estimates_are_defined_per_group
FAILED validator/tests/test_bench_full_eval.py::test_save_and_load_type_seeds
FAILED validator/tests/test_bench_full_eval.py::test_load_type_seeds_accepts_legacy_payload
3 failed, 1155 passed
```

</details>

<details>
<summary>After this branch — both images clean</summary>

```
##### swarm-pip-today (pip) #####
1159 passed, 2 skipped

##### swarm-uv-new (uv) #####
1159 passed, 2 skipped
```

</details>

The file was also run against the `ghcr.io/swarm-subnet/swarm:base` image published today: 28 passed.

The virtualenv fault was reproduced and then verified through the path it was reported on,
`.docker/docker-compose.yml`, with a dangling `.venv/bin/python` left in the tree throughout:

<details>
<summary>Before and after, same dangling venv present</summary>

```
before
  shutil.Error: [('/app/.venv/bin/python', ..., "[Errno 2] No such file or directory")]
  /usr/local/lib/python3.11/shutil.py:527: Error
  ERROR miner/tests/test_packaging.py::test_the_wheel_carries_the_miner_side
  4 passed, 1 error

after
  docker compose ... run --rm swarm_validator   1050 passed, 76 skipped
  docker compose ... run --rm swarm_miner         35 passed
```

</details>

### Tools & Dependencies

- Tools updated: none.
- Libraries / dependencies added or bumped (name + version): none.

### Is this a user-facing behavior change?

No. Test-only.

- [ ] Scoring, weights or epoch behavior changes
- [ ] Protocol version bumped - validators and miners have to match

### Risk & Rollback

Low risk; no production code is touched. The ignore change only adds patterns, so nothing that is
copied today stops being copied, and a virtualenv has no place in a built wheel regardless. Revert
either commit independently.

### Documentation

- [ ] README.md updated
- [ ] `docs/` updated
- [x] Not applicable (explain why): test-only change, no documented behaviour moves.

### Additional Information

The benchmark three run only under `--run-full`, so CI stays green either way. The virtualenv fault
is invisible to CI for a different reason: CI checks out fresh and never creates a venv, so only
someone who followed the install steps and then ran the suite locally hits it.

Both are worth fixing for the same reason - each one costs the next person time working out whether
their own change caused it, which is exactly what happened here.

### CODE REVIEW

**Review by robojules — CHANGES_REQUESTED** [review]
Test still are not passing, when executing:

`docker compose -f /home/julia-swarm/repositories/swarm/.docker/docker-compose.yml up --build swarm_miner`

There are still one error:


```
swarm_miner  | ==================================== ERRORS ====================================
swarm_miner  | ___________ ERROR at setup of test_the_wheel_carries_the_miner_side ____________
swarm_miner  | 
swarm_miner  | fixturedef = <FixtureDef argname='wheel_contents' scope='session' baseid=''>
swarm_miner  | request = <SubRequest 'wheel_contents' for <Function test_the_wheel_carries_the_miner_side>>
swarm_miner  | 
swarm_miner  |     @pytest.hookimpl(wrapper=True)
swarm_miner  |     def pytest_fixture_setup(fixturedef: FixtureDef, request) -> object | None:
swarm_miner  |         asyncio_mode = _get_asyncio_mode(request.config)
swarm_miner  |         if not _is_asyncio_fixture_function(fixturedef.func):
swarm_miner  |             if asyncio_mode == Mode.STRICT:
swarm_miner  |                 # Ignore async fixtures without explicit asyncio mark in strict mode
swarm_miner  |                 # This applies to pytest_trio fixtures, for example
swarm_miner  | >               return (yield)
swarm_miner  |                         ^^^^^
swarm_miner  | 
swarm_miner  | /usr/local/lib/python3.11/site-packages/pytest_asyncio/plugin.py:728: 
swarm_miner  | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
swarm_miner  | conftest.py:143: in wheel_contents
swarm_miner  |     shutil.copytree(repo_root, source, ignore=wheel_source_ignore())
swarm_miner  | /usr/local/lib/python3.11/shutil.py:573: in copytree
swarm_miner  |     return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
swarm_miner  | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
swarm_miner  | 
swarm_miner  | entries = [<DirEntry 'pytest.ini'>, <DirEntry '.env.example'>, <DirEntry 'README.md'>, <DirEntry '.ruff_cache'>, <DirEntry 'validator'>, <DirEntry 'champion_cf_swarm_autopilot_UID_99.zip'>, ...]
swarm_miner  | src = PosixPath('/app')
swarm_miner  | dst = PosixPath('/tmp/pytest-of-root/pytest-3/wheel_src0/repo')
swarm_miner  | symlinks = False
swarm_miner  | ignore = <function ignore_patterns.<locals>._ignore_patterns at 0x7cc9d5625e40>
swarm_miner  | copy_function = <function copy2 at 0x7cc9e85dd8a0>
swarm_miner  | ignore_dangling_symlinks = False, dirs_exist_ok = False
swarm_miner  | 
swarm_miner  |     def _copytree(entries, src, dst, symlinks, ignore, copy_function,
swarm_miner  |                   ignore_dangling_symlinks, dirs_exist_ok=False):
swarm_miner  |         if ignore is not None:
swarm_miner  |             ignored_names = ignore(os.fspath(src), [x.name for x in entries])
swarm_miner  |         else:
swarm_miner  |             ignored_names = ()
swarm_miner  |     
swarm_miner  |         os.makedirs(dst, exist_ok=dirs_exist_ok)
swarm_miner  |         errors = []
swarm_miner  |         use_srcentry = copy_function is copy2 or copy_function is copy
swarm_miner  |     
swarm_miner  |         for srcentry in entries:
swarm_miner  |             if srcentry.name in ignored_names:
swarm_miner  |                 continue
swarm_miner  |             srcname = os.path.join(src, srcentry.name)
swarm_miner  |             dstname = os.path.join(dst, srcentry.name)
swarm_miner  |             srcobj = srcentry if use_srcentry else srcname
swarm_miner  |             try:
swarm_miner  |                 is_symlink = srcentry.is_symlink()
swarm_miner  |                 if is_symlink and os.name == 'nt':
swarm_miner  |                     # Special check for directory junctions, which appear as
swarm_miner  |                     # symlinks but we want to recurse.
swarm_miner  |                     lstat = srcentry.stat(follow_symlinks=False)
swarm_miner  |                     if lstat.st_reparse_tag == stat.IO_REPARSE_TAG_MOUNT_POINT:
swarm_miner  |                         is_symlink = False
swarm_miner  |                 if is_symlink:
swarm_miner  |                     linkto = os.readlink(srcname)
swarm_miner  |                     if symlinks:
swarm_miner  |                         # We can't just leave it to `copy_function` because legacy
swarm_miner  |                         # code with a custom `copy_function` may rely on copytree
swarm_miner  |                         # doing the right thing.
swarm_miner  |                         os.symlink(linkto, dstname)
swarm_miner  |                         copystat(srcobj, dstname, follow_symlinks=not symlinks)
swarm_miner  |                     else:
swarm_miner  |                         # ignore dangling symlink if the flag is on
swarm_miner  |                         if not os.path.exists(linkto) and ignore_dangling_symlinks:
swarm_miner  |                             continue
swarm_miner  |                         # otherwise let the copy occur. copy2 will raise an error
swarm_miner  |                         if srcentry.is_dir():
swarm_miner  |                             copytree(srcobj, dstname, symlinks, ignore,
swarm_miner  |                                      copy_function, ignore_dangling_symlinks,
swarm_miner  |                                      dirs_exist_ok)
swarm_miner  |                         else:
swarm_miner  |                             copy_function(srcobj, dstname)
swarm_miner  |                 elif srcentry.is_dir():
swarm_miner  |                     copytree(srcobj, dstname, symlinks, ignore, copy_function,
swarm_miner  |                              ignore_dangling_symlinks, dirs_exist_ok)
swarm_miner  |                 else:
swarm_miner  |                     # Will raise a SpecialFileError for unsupported file types
swarm_miner  |                     copy_function(srcobj, dstname)
swarm_miner  |             # catch the Error from the recursive copytree so that we can
swarm_miner  |             # continue with other files
swarm_miner  |             except Error as err:
swarm_miner  |                 errors.extend(err.args[0])
swarm_miner  |             except OSError as why:
swarm_miner  |                 errors.append((srcname, dstname, str(why)))
swarm_miner  |         try:
swarm_miner  |             copystat(src, dst)
swarm_miner  |         except OSError as why:
swarm_miner  |             # Copying file access times may fail on Windows
swarm_miner  |             if getattr(why, 'winerror', None) is None:
swarm_miner  |                 errors.append((src, dst, str(why)))
swarm_miner  |         if errors:
swarm_miner  | >           raise Error(errors)
swarm_miner  | E           shutil.Error: [('/app/miner_env/bin/python', '/tmp/pytest-of-root/pytest-3/wheel_src0/repo/miner_env/bin/python', "[Errno 2] No such file or directory: '/app/miner_env/bin/python'"), ('/app/miner_env/bin/python3', '/tmp/pytest-of-root/pytest-3/wheel_src0/repo/miner_env/bin/python3', "[Errno 2] No such file or directory: '/app/miner_env/bin/python3'"), ('/app/miner_env/bin/python3.11', '/tmp/pytest-of-root/pytest-3/wheel_src0/repo/miner_env/bin/python3.11', "[Errno 2] No such file or directory: '/app/miner_env/bin/python3.11'")]
swarm_miner  | 
swarm_miner  | /usr/local/lib/python3.11/shutil.py:527: Error
swarm_miner  | =============================== warnings summary ===============================
swarm_miner  | ../usr/local/lib/python3.11/site-packages/starlette/formparsers.py:12
swarm_miner  |   /usr/local/lib/python3.11/site-packages/starlette/formparsers.py:12: PendingDeprecationWarning: Please use `import python_multipart` instead.
swarm_miner  |     import multipart
swarm_miner  | 
swarm_miner  | swarm/__init__.py:33
swarm_miner  |   /app/swarm/__init__.py:33: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
swarm_miner  |     import pkg_resources  # noqa: F401
swarm_miner  | 
swarm_miner  | -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
swarm_miner  | =========================== short test summary info ============================
swarm_miner  | ERROR miner/tests/test_packaging.py::test_the_wheel_carries_the_miner_side - ...
swarm_miner  | =================== 34 passed, 2 warnings, 1 error in 59.94s ===================
```


What it worries me is that this failure is not catched by the github action and it should, we should look further why, because this errors should be catched by default in the PR checks rather than needed to be executed on each end.



Validator tests also fails:

```
swarm_validator  | ==================================== ERRORS ====================================
swarm_validator  | ________ ERROR at setup of test_the_wheel_carries_what_an_install_needs ________
swarm_validator  | [gw3] linux -- Python 3.11.16 /usr/local/bin/python
swarm_validator  | 
swarm_validator  | fixturedef = <FixtureDef argname='wheel_contents' scope='session' baseid=''>
swarm_validator  | request = <SubRequest 'wheel_contents' for <Function test_the_wheel_carries_what_an_install_needs>>
swarm_validator  | 
swarm_validator  |     @pytest.hookimpl(wrapper=True)
swarm_validator  |     def pytest_fixture_setup(fixturedef: FixtureDef, request) -> object | None:
swarm_validator  |         asyncio_mode = _get_asyncio_mode(request.config)
swarm_validator  |         if not _is_asyncio_fixture_function(fixturedef.func):
swarm_validator  |             if asyncio_mode == Mode.STRICT:
swarm_validator  |                 # Ignore async fixtures without explicit asyncio mark in strict mode
swarm_validator  |                 # This applies to pytest_trio fixtures, for example
swarm_validator  | >               return (yield)
swarm_validator  |                         ^^^^^
swarm_validator  | 
swarm_validator  | /usr/local/lib/python3.11/site-packages/pytest_asyncio/plugin.py:728: 
swarm_validator  | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
swarm_validator  | conftest.py:143: in wheel_contents
swarm_validator  |     shutil.copytree(repo_root, source, ignore=wheel_source_ignore())
swarm_validator  | /usr/local/lib/python3.11/shutil.py:573: in copytree
swarm_validator  |     return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
swarm_validator  | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
swarm_validator  | 
swarm_validator  | entries = [<DirEntry 'pytest.ini'>, <DirEntry '.env.example'>, <DirEntry 'README.md'>, <DirEntry '.ruff_cache'>, <DirEntry 'validator'>, <DirEntry 'champion_cf_swarm_autopilot_UID_99.zip'>, ...]
swarm_validator  | src = PosixPath('/app')
swarm_validator  | dst = PosixPath('/tmp/pytest-of-root/pytest-3/popen-gw3/wheel_src0/repo')
swarm_validator  | symlinks = False
swarm_validator  | ignore = <function ignore_patterns.<locals>._ignore_patterns at 0x7aa202fe6a20>
swarm_validator  | copy_function = <function copy2 at 0x7aa25093c540>
swarm_validator  | ignore_dangling_symlinks = False, dirs_exist_ok = False
swarm_validator  | 
swarm_validator  |     def _copytree(entries, src, dst, symlinks, ignore, copy_function,
swarm_validator  |                   ignore_dangling_symlinks, dirs_exist_ok=False):
swarm_validator  |         if ignore is not None:
swarm_validator  |             ignored_names = ignore(os.fspath(src), [x.name for x in entries])
swarm_validator  |         else:
swarm_validator  |             ignored_names = ()
swarm_validator  |     
swarm_validator  |         os.makedirs(dst, exist_ok=dirs_exist_ok)
swarm_validator  |         errors = []
swarm_validator  |         use_srcentry = copy_function is copy2 or copy_function is copy
swarm_validator  |     
swarm_validator  |         for srcentry in entries:
swarm_validator  |             if srcentry.name in ignored_names:
swarm_validator  |                 continue
swarm_validator  |             srcname = os.path.join(src, srcentry.name)
swarm_validator  |             dstname = os.path.join(dst, srcentry.name)
swarm_validator  |             srcobj = srcentry if use_srcentry else srcname
swarm_validator  |             try:
swarm_validator  |                 is_symlink = srcentry.is_symlink()
swarm_validator  |                 if is_symlink and os.name == 'nt':
swarm_validator  |                     # Special check for directory junctions, which appear as
swarm_validator  |                     # symlinks but we want to recurse.
swarm_validator  |                     lstat = srcentry.stat(follow_symlinks=False)
swarm_validator  |                     if lstat.st_reparse_tag == stat.IO_REPARSE_TAG_MOUNT_POINT:
swarm_validator  |                         is_symlink = False
swarm_validator  |                 if is_symlink:
swarm_validator  |                     linkto = os.readlink(srcname)
swarm_validator  |                     if symlinks:
swarm_validator  |                         # We can't just leave it to `copy_function` because legacy
swarm_validator  |                         # code with a custom `copy_function` may rely on copytree
swarm_validator  |                         # doing the right thing.
swarm_validator  |                         os.symlink(linkto, dstname)
swarm_validator  |                         copystat(srcobj, dstname, follow_symlinks=not symlinks)
swarm_validator  |                     else:
swarm_validator  |                         # ignore dangling symlink if the flag is on
swarm_validator  |                         if not os.path.exists(linkto) and ignore_dangling_symlinks:
swarm_validator  |                             continue
swarm_validator  |                         # otherwise let the copy occur. copy2 will raise an error
swarm_validator  |                         if srcentry.is_dir():
swarm_validator  |                             copytree(srcobj, dstname, symlinks, ignore,
swarm_validator  |                                      copy_function, ignore_dangling_symlinks,
swarm_validator  |                                      dirs_exist_ok)
swarm_validator  |                         else:
swarm_validator  |                             copy_function(srcobj, dstname)
swarm_validator  |                 elif srcentry.is_dir():
swarm_validator  |                     copytree(srcobj, dstname, symlinks, ignore, copy_function,
swarm_validator  |                              ignore_dangling_symlinks, dirs_exist_ok)
swarm_validator  |                 else:
swarm_validator  |                     # Will raise a SpecialFileError for unsupported file types
swarm_validator  |                     copy_function(srcobj, dstname)
swarm_validator  |             # catch the Error from the recursive copytree so that we can
swarm_validator  |             # continue with other files
swarm_validator  |             except Error as err:
swarm_validator  |                 errors.extend(err.args[0])
swarm_validator  |             except OSError as why:
swarm_validator  |                 errors.append((srcname, dstname, str(why)))
swarm_validator  |         try:
swarm_validator  |             copystat(src, dst)
swarm_validator  |         except OSError as why:
swarm_validator  |             # Copying file access times may fail on Windows
swarm_validator  |             if getattr(why, 'winerror', None) is None:
swarm_validator  |                 errors.append((src, dst, str(why)))
swarm_validator  |         if errors:
swarm_validator  | >           raise Error(errors)
swarm_validator  | E           shutil.Error: [('/app/miner_env/bin/python', '/tmp/pytest-of-root/pytest-3/popen-gw3/wheel_src0/repo/miner_env/bin/python', "[Errno 2] No such file or directory: '/app/miner_env/bin/python'"), ('/app/miner_env/bin/python3', '/tmp/pytest-of-root/pytest-3/popen-gw3/wheel_src0/repo/miner_env/bin/python3', "[Errno 2] No such file or directory: '/app/miner_env/bin/python3'"), ('/app/miner_env/bin/python3.11', '/tmp/pytest-of-root/pytest-3/popen-gw3/wheel_src0/repo/miner_env/bin/python3.11', "[Errno 2] No such file or directory: '/app/miner_env/bin/python3.11'")]
swarm_validator  | 
swarm_validator  | /usr/local/lib/python3.11/shutil.py:527: Error
swarm_validator  | =============================== warnings summary ===============================
swarm_validator  | swarm/__init__.py:33
swarm_validator  | swarm/__init__.py:33
swarm_validator  | swarm/__init__.py:33
swarm_validator  | swarm/__init__.py:33
```

**Review by robojules — APPROVED** [review]
LGTM
